services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.12
    container_name: clickhouse_lab5
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./common/sql/events/clickhouse/01_users.sql:/docker-entrypoint-initdb.d/users.sql
      - ./common/sql/events/clickhouse/10_clickhouse_events.sql:/docker-entrypoint-initdb.d/init.sql
      - ./common/data/events:/var/lib/clickhouse/user_files/events
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: postgres_lab5
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./common/sql/events/postgres/10_postgres_events.sql:/docker-entrypoint-initdb.d/init.sql
      - ./common/data/events:/data/events
    restart: unless-stopped

volumes:
  clickhouse_data:
  postgres_data:
