services:
  generator:
    build:
      context: ./common/dockerfiles/events-generator
      dockerfile: Dockerfile
    image: events_generator
    container_name: events_generator_lab5
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./labs/lab5/data:/data
    command: ["python", "generate_events.py", "--output", "/data"]

  clickhouse:
    image: clickhouse/clickhouse-server:25.12
    container_name: clickhouse_lab5
    depends_on:
      generator:
        condition: service_completed_successfully
    ports:
      - "8123:8123"
      - "19000:9000"
    volumes:
      - clickhouse_data_lab5:/var/lib/clickhouse
      - ./labs/lab5/data:/var/lib/clickhouse/user_files/events
      - ./common/sql/events/clickhouse/01_users.sql:/docker-entrypoint-initdb.d/users.sql
      - ./common/sql/events/clickhouse/10_clickhouse_events.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: postgres_lab5
    depends_on:
      generator:
        condition: service_completed_successfully
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_lab5:/var/lib/postgresql/data
      - ./common/sql/events/postgres/10_postgres_events.sql:/docker-entrypoint-initdb.d/init.sql
      - ./labs/lab5/data:/data/events:ro
    restart: unless-stopped

volumes:
  clickhouse_data_lab5:
  postgres_data_lab5:
